// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPCAPP.TicketWeb.Data;

namespace SPCAPP.TicketWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220120162214_autoSpc")]
    partial class autoSpc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SPCAPP.TicketWeb.Models.TicketSpc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Avance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CerradoId")
                        .HasColumnType("int");

                    b.Property<string>("CodAux")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpbAno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpbNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAvance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTrabajo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fk_procede")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fono_contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HrsInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HrsPrograma")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("HrsPrograma1")
                        .HasColumnType("time");

                    b.Property<DateTime?>("HrsTermino")
                        .HasColumnType("datetime2");

                    b.Property<string>("Medio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passwords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Programado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proyecto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProyectoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Realizado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tecnico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trabajo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCierre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreaTk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Visita")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicketSpc");
                });
#pragma warning restore 612, 618
        }
    }
}
